version: "3.9"

services:
  rabbitnq:
    image: rabbitmq:latest
    container_name: session-queue
    ports: 
      - "5672:5672"
  session-service:
    build: "."
    image: session-service:latest
    container_name: session-service
    ports:
      - "5001:5001"
    depends_on: [rabbitnq]
    working_dir: /usr/src/app
    command: python3 ./server.py
    volumes:
      - ./app/.log/:/usr/src/app/.log
    environment:
      - RABBITMQ_SERVICE_IP=session-queue
      - RABBITMQ_SERVICE_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
