version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: session-queue
    ports:
      - "5672:5672"
    networks:
      - backend
  session-status-service:
    image: session-service:latest
    container_name: session-status-service
    depends_on: [rabbitmq, session-service]
    working_dir: /usr/src/app
    volumes:
      - ./.log/:/usr/src/app/.log:cached
    env_file:
      - rabbitmq-variables.env
      - firebase-variables.env
    environment:
      - MODE=SESSION-STATUS-SERVICE
    networks:
      - backend
    restart: always
  session-service:
    build: "."
    image: session-service:latest
    container_name: session-service
    ports:
      - "5001:5001"
    depends_on: [rabbitmq]
    links:
      - rabbitmq
    networks:
      - backend
    working_dir: /usr/src/app
    volumes:
      - ./.log/:/usr/src/app/.log:cached
    env_file:
      - rabbitmq-variables.env
      - firebase-variables.env
    environment:
      - MODE=SESSION-SERVICE
    restart: always
networks:
  backend:
